---
booktitle: Proceedings of the 3rd Machine Learning for Healthcare Conference
volume: 85
shortname: MLHC
year: '2018'
start: 2018-08-17
end: 2018-08-18
published: 2018-11-29
url: http://proceedings.mlr.press
author:
  name: PMLR
conference_number: '3'
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: MLHC-2018
month: 0
cycles: false
bibtex_editor: Doshi-Velez, Finale and Fackler, Jim and Jung, Ken and Kale, David
  and Ranganath, Rajesh and Wallace, Byron and Wiens, Jenna
editor:
- given: Finale
  family: Doshi-Velez
- given: Jim
  family: Fackler
- given: Ken
  family: Jung
- given: David
  family: Kale
- given: Rajesh
  family: Ranganath
- given: Byron
  family: Wallace
- given: Jenna
  family: Wiens
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 3rd Machine Learning for Healthcare Conference
    Held in Palo Alto, California on 17-18 August 2018

  Published as Volume 85 by the Proceedings of Machine Learning Research on 29 November 2018.

  Volume Edited by:
    Finale Doshi-Velez
    Jim Fackler
    Ken Jung
    David Kale
    Rajesh Ranganath
    Byron Wallace
    Jenna Wiens

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 17--18 Aug
baseurl: "/v85"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v85
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Machine Learning for Healthcare Conference
  url: 
  location: Palo Alto, California
  dates:
  - 2018-08-17
  - 2018-08-18
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
